package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;
  public static final int Square = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x257252e62cc94d53L, 0xb72d33debe928ca4L);
    builder.put(0x7d19d7af1a7d4180L, Canvas);
    builder.put(0x7d19d7af1a7d416cL, Circle);
    builder.put(0x7d19d7af1a7e2f23L, Color);
    builder.put(0x7d19d7af1a7eb008L, ColorReference);
    builder.put(0x7d19d7af1a7d416bL, Shape);
    builder.put(0x7d19d7af1a7d4176L, Square);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
