package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCanvas = createDescriptorForCanvas();
  /*package*/ final ConceptDescriptor myConceptCircle = createDescriptorForCircle();
  /*package*/ final ConceptDescriptor myConceptColor = createDescriptorForColor();
  /*package*/ final ConceptDescriptor myConceptColorReference = createDescriptorForColorReference();
  /*package*/ final ConceptDescriptor myConceptShape = createDescriptorForShape();
  /*package*/ final ConceptDescriptor myConceptSquare = createDescriptorForSquare();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCanvas, myConceptCircle, myConceptColor, myConceptColorReference, myConceptShape, myConceptSquare);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Canvas:
        return myConceptCanvas;
      case LanguageConceptSwitch.Circle:
        return myConceptCircle;
      case LanguageConceptSwitch.Color:
        return myConceptColor;
      case LanguageConceptSwitch.ColorReference:
        return myConceptColorReference;
      case LanguageConceptSwitch.Shape:
        return myConceptShape;
      case LanguageConceptSwitch.Square:
        return myConceptSquare;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCanvas() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Canvas", 0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7d4180L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:276e9c7f-5fe5-4921-83c2-8dce1c27d69d(Shapes.structure)/9014473276222423424");
    b.version(2);
    b.aggregate("shapes", 0x7d19d7af1a7d4183L).target(0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7d416bL).optional(true).ordered(true).multiple(true).origin("9014473276222423427").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForCircle() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Circle", 0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7d416cL);
    b.class_(false, false, false);
    b.super_("Shapes.structure.Shape", 0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7d416bL);
    b.origin("r:276e9c7f-5fe5-4921-83c2-8dce1c27d69d(Shapes.structure)/9014473276222423404");
    b.version(2);
    b.property("x", 0x7d19d7af1a7d416dL).type(PrimitiveTypeId.INTEGER).origin("9014473276222423405").done();
    b.property("y", 0x7d19d7af1a7d416fL).type(PrimitiveTypeId.INTEGER).origin("9014473276222423407").done();
    b.property("radius", 0x7d19d7af1a7d4172L).type(PrimitiveTypeId.INTEGER).origin("9014473276222423410").done();
    b.alias("circle");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColor() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Color", 0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7e2f23L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:276e9c7f-5fe5-4921-83c2-8dce1c27d69d(Shapes.structure)/9014473276222484259");
    b.version(2);
    b.alias("color");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForColorReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "ColorReference", 0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7eb008L);
    b.class_(false, false, false);
    b.origin("r:276e9c7f-5fe5-4921-83c2-8dce1c27d69d(Shapes.structure)/9014473276222517256");
    b.version(2);
    b.associate("target", 0x7d19d7af1a7eb009L).target(0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7e2f23L).optional(false).origin("9014473276222517257").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForShape() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Shape", 0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7d416bL);
    b.class_(false, true, false);
    b.origin("r:276e9c7f-5fe5-4921-83c2-8dce1c27d69d(Shapes.structure)/9014473276222423403");
    b.version(2);
    b.aggregate("color", 0x7d19d7af1a7eb038L).target(0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7eb008L).optional(false).ordered(true).multiple(false).origin("9014473276222517304").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSquare() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Shapes", "Square", 0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7d4176L);
    b.class_(false, false, false);
    b.super_("Shapes.structure.Shape", 0x257252e62cc94d53L, 0xb72d33debe928ca4L, 0x7d19d7af1a7d416bL);
    b.origin("r:276e9c7f-5fe5-4921-83c2-8dce1c27d69d(Shapes.structure)/9014473276222423414");
    b.version(2);
    b.property("upperLeftX", 0x7d19d7af1a7d4177L).type(PrimitiveTypeId.INTEGER).origin("9014473276222423415").done();
    b.property("upperLeftY", 0x7d19d7af1a7d4179L).type(PrimitiveTypeId.INTEGER).origin("9014473276222423417").done();
    b.property("size", 0x7d19d7af1a7d417cL).type(PrimitiveTypeId.INTEGER).origin("9014473276222423420").done();
    b.alias("square");
    return b.create();
  }
}
